Feat/#19 desktop view qa issue
BCSDLab/KOIN_COOP_WEB pull request #20
Opened 2024-10-13 12:16 UTC by JeongWon-CHO

- Close #19 
  
## What is this PR? 🔍

- 기능 : 날짜 이동 버튼 추가 / 엑셀 다운로드 모달창 수정 / 모바일 뷰 구조 수정
- issue : #19 

## Changes 📝

### '날짜 이동 버튼'추가
*  ‘오늘' 버튼을 누르면 오늘 날짜가 있는 주 or 달 로 이동합니다.
* ‘<’, ‘>’ 버튼을 누르면 다른 주 or 달의 식단을 모두 조회할 수 있습니다.

### 엑셀 다운로드 모달창 수정
* 모달창 설명 문구 변경
> '식단은 2022/11/29 부터 다운받을 수 있어요.' 로 수정되었습니다.

<br>

* 엑셀 다운로드 에러 툴팁 추가
1. 시작일 또는 종료일이 오늘 날짜 이후를 나타내는 경우
2.  시작일이 2022/11/29 이전의 날짜인 경우
3. 시작일이 종료일 이후인 경우

### 주간/월간 식단 오타 수정
* 월간일 때는 '월간 식단', 주간일 때는 '주간 식단'이 뜨도록 수정하였습니다.

### 모바일뷰 구조 수정
* 오늘 버튼을 추가함으로써 주간/월간 선택 버튼이 상단으로 이동하였습니다.
* 상단 설정 버튼을 메뉴 아이콘으로 바꾸고 상세 페이지로 이동하는 것이 아닌, 드롭다운으로 변경하였습니다.

## ScreenShot 📷

<img width="223" alt="image" src="https://github.com/user-attachments/assets/af69f40d-76ea-478f-bc93-ba4087481d4f">

기본 상태입니다.

<img width="223" alt="image" src="https://github.com/user-attachments/assets/31d6d0a4-10ac-4a82-be6e-6ebb17000f49">

호버 상태입니다.

<br>

<img width="395" alt="image" src="https://github.com/user-attachments/assets/69dc3477-2efb-4cef-8261-877102ab79c0">

변경된 모달창 설명 문구입니다.

<img width="526" alt="image" src="https://github.com/user-attachments/assets/303e292b-c243-4234-8c74-329221dedc52">

시작일 또는 종료일이 오늘 날짜 이후를 나타내는 경우입니다.

<img width="518" alt="image" src="https://github.com/user-attachments/assets/fed1483c-2bfd-44f4-8b40-ec1581655259">

시작일이 2022/11/29 이전의 날짜인 경우입니다.

<img width="518" alt="image" src="https://github.com/user-attachments/assets/9dfc1471-5e55-496f-a6ec-b769f695375b">

시작일이 종료일 이후인 경우입니다.

<br>

<img width="215" alt="image" src="https://github.com/user-attachments/assets/15f2d3c5-df52-4260-a103-41a90820c2a7">
<img width="219" alt="image" src="https://github.com/user-attachments/assets/fe08ae80-242e-4dd5-8dc1-b72639dcde11">

월간일 때는 '월간 식단', 주간일 때는 '주간 식단'이 뜹니다.

<br>
<img width="349" alt="image" src="https://github.com/user-attachments/assets/3dea5513-b0f5-4661-ad1d-e4ee8b4b8afe">

주간/월간 선택 버튼이 상단으로 이동하였습니다.

<img width="349" alt="image" src="https://github.com/user-attachments/assets/ff9f6017-1541-4f57-ad17-6c22afc7e809">
상단 설정 버튼을 메뉴 아이콘으로 바꾸고, 드롭다운으로 변경하였습니다.

## Test CheckList ✅

- [x] Excel 다운 에러 1 : 시작일 또는 종료일이 오늘 날짜 이후를 나타내는 경우
- [x] Excel 다운 에러 2 : 시작일이 2022/11/29 이전의 날짜인 경우
- [x] Excel 다운 에러 3 : 시작일이 종료일 이후인 경우

## Precaution

## ✔️ Please check if the PR fulfills these requirements

- [x] It's submitted to the correct branch, not the `develop` branch unconditionally?
- [x] If on a hotfix branch, ensure it targets `main`?
- [x] There are no warning message when you run `yarn lint`

2024-10-14 00:35 UTC, daepan requested changes
기능 추가를 위해 React-Tooltip을 예쁘게 잘 사용하셨군요. 수고하셨습니다.
코드 내용에 대해서 몇가지 피드백을 남겨봤습니다. 잘 고민하시고 수정해주시면 감사하겠습니다.

2024-10-14 00:35 UTC, daepan commented on src/layout/Header/Dropdown.tsx
> +export default Dropdown;
헤더에서 드롭다운이라 네이밍이 뭔가 단순해서 앞으로 드롭 다운 기능이 생길지도 모르는데 조금 걱정되네요 다른 좋은 네이밍이 있지 않을까요?
모바일에서만 사용하는 것 같은데 모바일 드롭다운이라는 한정을 두면 어떨까 합니다.

2024-10-14 00:35 UTC, daepan commented on src/layout/Header/index.tsx
> +                jsx-a11y/click-events-have-key-events */}
린트를 제거하셨군요. 린트는 우리가 코드를 쓰면서 지키기 위한 룰입니다.
제거하신 이유가 있다면 그 이유를 상세히 적어주시고, 지킬 수 있는 룰이라면 제대로 지켜주시면 좋을 것 같습니다.

2024-10-14 00:35 UTC, daepan commented on src/layout/Header/index.tsx
> +                jsx-a11y/click-events-have-key-events */}
단순히 본인이 편함을 위해 사용하지 말아주셨으면 좋겠습니다.

2024-10-14 00:35 UTC, daepan commented on src/pages/Coop/components/Calendar/index.tsx
> +                {`${selectedDate.getMonth() + 1}월 ${selectedDate.getDate()}일 ${DAYS[selectedDate.getDay()]}요일`}
이거 반복되는 것 같네요 따로 함수로 쳐도 좋을 것 같습니다. 아니면 다른 쪽에도 사용했을수도?

2024-10-14 00:35 UTC, daepan commented on src/pages/Coop/components/DownloadModal/index.tsx
>      }
조건문을 early return을 사용해서 따로 하셨네요. else를 사용하면 에러코드가 최상단의 조건을 우선으로 처리할 것 같고 코드를 하나로 단일하게 할 수 있을 것 같습니다. if 3번 early보다는 return을 한번만 해주는게 좀 더 잘 읽힐 것 같습니다.
또한 에러코드 1,2,3 으로 선언되어있는데 각 코드가 어떤걸 의미하는지 아직 이해 잘 되지 않습니다. 이렇게 값을 하드코딩하게 되면 앞으로 서비스에서 유지보수하러 들어오는 신입부원들에게 좋지 않은 영향을 줄 수 있다고 생각합니다.
요즘 주변에서 우아한 테크코스 준비하신다고 하니 비슷한 예시로 우테코 교육과정에서 하드코딩에 대한 많은 생각을 주는 [내용](https://velog.io/@kyw0716/%ED%94%84%EB%A6%AC%EC%BD%94%EC%8A%A4-%EB%8B%A4%EC%8B%9C-%ED%92%80%EA%B8%B0-%EC%88%AB%EC%9E%90-%EC%95%BC%EA%B5%AC)이 있으니 한번 해당 하드 코딩을 수정해주시면 좋을 것 같습니다.

2024-10-14 02:07 UTC, haejinyun reviewed
수고하셨습니다!!

이것저것 보다보니 여러 리뷰를 달았네요.. 지금 당장 수정해야할 것도 고민해보면 좋은 것도 달아보았습니다! 확인하시고 괜찮다고 생각신 것, 적용할 것만 적용해주세요! 

* 제가 해당 프로젝트 테스트 아이디가 없어서 접속을 해서 확인을 해보지 못했습니다.. 
리뷰 확인시 해당 부분 고려해주시면 감사하겠습니다..! 죄송합니다ㅠㅠ

2024-10-14 02:07 UTC, haejinyun commented on src/layout/Header/Dropdown.module.scss
> +  z-index: 1000;
개발하다보면 z-index를 쓰는 경우가 많죠!!
그래서 이런 상수 값을 잘 정리해야하는 경우가 있는 것 같아요
누군가가 너무 크게 설정했는데 이것이 공유가 되지 않으면, 다른 사람이 개발을 하다가 왜 z-index를 높게 줘도 안올라오지..? 하는 상황이 있을 수 있거든요! 
한번 적절한 z-index에 대해서 생각해봐도 좋을 것 같아요~

2024-10-14 02:07 UTC, haejinyun commented on src/layout/Header/index.tsx
> +  const [view, setView] = useState(false);
코드를 살펴보니 `useBooleanState` 라는 훅이 이미 존재하네요~
view가 boolean값으로 t/f만을 처리하는 것이라면 이미 정의 된 커스텀 훅을 활용해 주는게 다른 사람들이 봤을 때 코드 이해하기가 더 쉬울 것 같네요~

2024-10-14 02:07 UTC, haejinyun commented on src/layout/Header/index.tsx
> +        {isMobile ? (
얘는 제가 사이트 계정을 몰라서 들어가서 보지는 못했네요ㅠㅠ
만약 모바일에서만 보이는 것이라면 `&&`를 써서 표현하는 것도 좋을 것 같아요.
아니면 모바일과 웹이 아주 많이 다르다면 아예 컴포넌트를 따로 파서 조건부 렌더링을 해주는 것도 나쁘지 않은 방법이라고 생각합니다~ ( 이건 추후 상세한 개발 시에 고려해주세요~)

2024-10-14 02:07 UTC, haejinyun commented on src/layout/Header/index.tsx
> +                {view && <Dropdown />}
이런 방향도 좋은 데 만약 Dropdown이라는 컴포넌트에 view라는 속성을 props로 받는 방향은 어떻게 생각하시나요?
```suggestion
                <Dropdown view={view} />
```
이런식으로 보여질지 아닐지가 조건부 렌더링으로 들어가는 것이 아니라 인자로 들어가서 Dropdown 내부에서 판단이 되는 것이지요!

2024-10-14 02:07 UTC, haejinyun commented on src/pages/Coop/components/Calendar/Calendar.module.scss
> +  line-height: 160%; /* 22.4px */
주석은 지워주는 것이 좋을 것 같네요!

2024-10-14 02:07 UTC, haejinyun commented on src/pages/Coop/components/Calendar/index.tsx
> +  };
제 생각에는 해당 함수가 하는 일이 많은 것 같아요.

1. api res의 타입에 따라서 하는 일이 달라짐
2. 방향에 따라서 하는 일이 달라짐.

이게 중첩되어 엮여 있으니 좋다고 느껴지지는 않을 것 같아요..
해당 함수가 기능을 수행하는데 문제가 없다면 당장 수정이 필요하지는 않지만, 이후 시간이 날때 위 함수를 잘 분리하고 가독성이 높히는 과정을 거쳐보면 좋을 것 같아요~

함수를 쪼개는 것도 한번 알아보면 좋을 것 같다고 생각합니다!

2024-10-14 02:07 UTC, haejinyun commented on src/pages/Coop/components/Calendar/index.tsx
> +                {`${selectedDate.getMonth() + 1}월 ${selectedDate.getDate()}일 ${DAYS[selectedDate.getDay()]}요일`}
유틸 훅으로 하나 만들어서 쓰는 것도 좋을듯합니다잇

2024-10-14 02:07 UTC, haejinyun commented on src/pages/Coop/components/Calendar/index.tsx
> +      {isMobile ? (
코드가 상당한데 혹시 모바일과 웹의 디자인이 많이 다른가요..?
이것도 제가 아이디가 없어서 확인은 못해봤지만ㅜㅠㅜ
많이 다르다면 컴포넌트를 따로 파주는 것이 편할 것 같기도 하네요...

많이 다르지 않다면, 두 부분에서 다른 쪽만 조건부로 감싸는건 어떤가요? 
삼항연산자로 다르게 렌더링 시키는 즉 영역을 줄여보는 것이지요~

2024-10-14 02:07 UTC, haejinyun commented on src/pages/Coop/components/DateMover/index.tsx
> +      </div>
버튼이면 button 태그를 써주는게 더 좋을 것 같네요!
시멘틱 태그에 대해서 한번 알아보는 것도 좋을 것 같아요~

버튼 태그를 쓰면 key와 관련된 속성을 넘겨줄 필요가 없어요!
아마 div를 써서 key 입력에 대응해라~!! 이런 lint에러가 났을 것 같네요ㅋ큐ㅠ

2024-10-14 02:07 UTC, haejinyun commented on src/pages/Coop/components/DiningDownload/index.tsx
> +        <div className={styles['dining-download-button']}>식단 파일 다운로드</div>
얘도 왜 button이었다가 div가 되었을까요ㅠㅠ

2024-10-14 02:07 UTC, haejinyun commented on src/pages/Coop/components/DownloadModal/DownloadModal.module.scss
> +  width: 128px;
한가지 팁을 드리자면 button이나 어떤 요소에 width를 잡기보다는 max와 min을 쓰고 padding으로 영역을 잡는 것이 반응형을 대응하기 더 쉬운 방법이라고 생각합니다!

2024-10-14 02:07 UTC, haejinyun commented on src/pages/Coop/components/DownloadModal/index.tsx
> +    return `${date.year.toString()}-${date.month.toString().padStart(2, '0')}-${date.day.toString().padStart(2, '0')}`;
이렇게 각각 toString으로 변하게 할꺼면 위에서 타입을 지정할 때 string으로 하지 않은 이유는 무엇인가요?

2024-10-14 13:29 UTC, JeongWon-CHO commented on src/layout/Header/Dropdown.tsx
> +export default Dropdown;
`MobileDropdown` 으로 수정했습니다 !

2024-10-15 05:54 UTC, MinGu-Jeong commented on src/layout/Header/index.tsx
> +// import SearchIcon from 'assets/svg/auth/search-icon.svg?react';
사용하지 않는 svg라면 제거해주셔도 좋을 것 같아요!

2024-10-15 05:56 UTC, MinGu-Jeong commented on src/layout/Header/index.tsx
> +                {/* <SearchIcon className={styles.search} /> */}
이건 다음 기획에 예정되어있는 기능인가요?

2024-10-15 05:57 UTC, MinGu-Jeong commented on src/layout/Header/index.tsx
> +            <Setting1 />
`Setting1`말고 더 적절한 네이밍은 없을까요?
코드만 보고 어떤 컴포넌트가 보여질지 잘 예상이 안가는것 같습니다

2024-10-15 06:17 UTC, D0Dam commented on src/layout/Header/index.tsx
> +            <Setting1 />
`HeaderNavigation`으로 변경하고 header 컴포넌트 하위로 해당 컴포넌트 위치 변경했습니다!

2024-10-15 06:17 UTC, D0Dam commented on src/layout/Header/index.tsx
> +                {/* <SearchIcon className={styles.search} /> */}
네 맞습니다!

2024-10-15 07:25 UTC, JeongWon-CHO commented on src/layout/Header/index.tsx
> +                jsx-a11y/click-events-have-key-events */}
기존 코드는 `<div>` 태그를 `button`으로 사용하려고 했었습니다..!
버튼 안에 글씨와 이미지를 모두 넣어야 하는 상황이었는데, `<button>` 안에 이미지를 넣는 것보다 `<div>` 안에 이미지를 넣는 코드가 더 간략해 보여서 해당 방법으로 작성하였습니다.

그런데 이렇게 쓰면 eslint 관련 에러가 뜨길래 검색해 보니, `<div>`를 `button`으로 사용하려고 할 때 eslint에 걸린다고 하였습니다. eslint를 제거하는 코드를 추가하면 해결된다고 봐서 큰 생각 없이 추가했습니다. 이 부분까지는 미처 고려하지 못한 거 같습니다..! 다음부터는 좀 더 신경써서 작성하도록 하겠습니다 !

현재는 `<button>` 태그로 변경하여서 해당 코드는 사라졌습니다 !

2024-10-15 07:48 UTC, JeongWon-CHO commented on src/pages/Coop/components/DateMover/index.tsx
> +      </div>
버튼 안에 이미지가 들어가는 상황이었는데,
`button` 태그에 텍스트와 이미지를 넣는 것보다
`div` 태그에 텍스트와 이미지를 담는 게 코드가 더 깔끔해 보여서 이렇게 진행했었습니다..!

말씀해 주신 것처럼 `div` 태그를 사용했기에 lint 에러가 났습니다.. 현재는 `button` 태그로 고쳤습니다 !

2024-10-15 12:08 UTC, JeongWon-CHO commented on src/pages/Coop/components/Calendar/index.tsx
> +                {`${selectedDate.getMonth() + 1}월 ${selectedDate.getDate()}일 ${DAYS[selectedDate.getDay()]}요일`}
함수로 만들어 반영하였습니다 ..!

2024-10-15 12:08 UTC, JeongWon-CHO commented on src/layout/Header/Dropdown.module.scss
> +  z-index: 1000;
찾아보니까 z-index의 최댓값은 2,147,483,647이라고 하는데, 이렇게 큰 값까지 지정하는 경우는 드물고, 일반적으로 100 이하의 값이면 충분하다고 합니다..!
다른 요소에는 z-index 속성을 쓴 곳이 없어서 우선 적당히 `10` 의 값으로 주었습니다 !

2024-10-15 12:09 UTC, JeongWon-CHO commented on src/pages/Coop/components/Calendar/Calendar.module.scss
> +  line-height: 160%; /* 22.4px */
반영했습니다 !!

2024-10-15 12:10 UTC, JeongWon-CHO commented on src/pages/Coop/components/DiningDownload/index.tsx
> +        <div className={styles['dining-download-button']}>식단 파일 다운로드</div>
제가 button 태그의 css 이해도가 부족했어서, 디자인과 살짝 안 맞는 부분들의 원인을 `button` 태그가 가지고 있는 기본 css 설정 때문이라고 생각했기에 `div` 태그로 바꾸었습니다. 현재는 `button` 태그로 바꾸었습니다 !

2024-10-15 12:10 UTC, JeongWon-CHO commented on src/pages/Coop/components/DownloadModal/DownloadModal.module.scss
> +  width: 128px;
width 속성 대신 padding으로 영역을 잡아서 반영했습니다, 감사합니다 !

2024-10-15 12:40 UTC, JeongWon-CHO commented on src/layout/Header/index.tsx
> +  const [view, setView] = useState(false);
헉... 감사합니다 !
`useBooleanState` 훅을 사용해서 가독성이 높아지도록 반영하였습니다..!!

2024-10-15 12:45 UTC, JeongWon-CHO commented on src/layout/Header/index.tsx
> +        {isMobile ? (
모바일과 데스크탑의 헤더가 다르기 때문에 이렇게 작성하였습니다..!

2024-10-15 13:10 UTC, JeongWon-CHO commented on src/layout/Header/index.tsx
> +                {view && <Dropdown />}
감사합니다, 반영하였습니다 !

2024-10-15 13:44 UTC, JeongWon-CHO commented on src/pages/Coop/components/DownloadModal/index.tsx
>      }
말씀해 주신 내용 잘 알겠습니다 !!
에러코드는 별 생각 없이 1, 2, 3으로 선언하였는데, 당장이 급해서 차마 유지보수까지는 생각하지 못하였던 거 같습니다.. 다음부터는 생각을 좀 더 하고 코드를 짜도록 하겠습니다..!
현재 해당 코드는 삭제되었으며, 추후에 비슷한 상황이 생긴다면 말씀해 주신 방법대로 반영하도록 하겠습니다 ..!

2024-10-15 13:45 UTC, JeongWon-CHO commented on src/pages/Coop/components/DownloadModal/index.tsx
> +    return `${date.year.toString()}-${date.month.toString().padStart(2, '0')}-${date.day.toString().padStart(2, '0')}`;
날짜 입력 칸에 문자가 들어가는 것을 방지하기 위해 이렇게 했습니다..!
그런데 api는 날짜를 `string` 으로 받아서 변환 과정이 필요했습니다..

2024-10-15 13:53 UTC, JeongWon-CHO commented on src/pages/Coop/components/Calendar/index.tsx
> +      {isMobile ? (
여러 부분이 작게 작게 달라서 컴포넌트로 따로 빼기도 애매하고 조건부도 애매하다고 생각하여서 이렇게 했습니다...!!

2024-10-15 13:59 UTC, D0Dam approved these changes
첫 이슈였는데 그래도 잘 해결해 주셨습니다! 수고하셨습니다!

2024-10-15 14:17 UTC, junghaesung79 reviewed
고생 많으셨어요!!!
나중에 어프루브는 트랙장님께 부탁드리면 좋을 것 같아요~~

2024-10-15 14:17 UTC, junghaesung79 commented on src/pages/Coop/components/Calendar/Calendar.module.scss
> +  display: flex;
클래스명으로써 네 어절은 조금 긴 것 같아요. 저는 보통 1~2 어절로 사용하는 것을 좋아하는데 어떻게 생각하시나요?

2024-10-15 14:17 UTC, junghaesung79 commented on src/pages/Coop/components/Calendar/Calendar.module.scss
> +  line-height: 160%;
font에는 여러 속성이 있죠. 그 속성들은 기본값을 가지고 있어요. 이 기본 값은 명시적으로 적을 수도, 생략할 수도 있어요. 저는 예전에는 적어주다가 지금은 생략하는 것을 선호해요. 그 이유는 아무래도 기본 값이기 때문에 일반적인 상황에서 기본 값을 갖고 있는 경우가 많기 때문이예요. 지금 보시면 normal과 400이 기본 값인데, 한번 이 값이 기본 값임을 의식한 뒤로는 지우게 되더라구요. 하지만 이 부분에 대해서 팀에서 약속된 내용은 없어서 그냥 한 번 나는 어떤 방법이 더 좋은가 생각해보시면 좋을 것 같아요😁
제가 말한 기본 값으로 어떤 값을 갖는 지 한 번 찾아보세요~

[참고](https://ofcourse.kr/css-course/font-%EC%86%8D%EC%84%B1)

2024-10-15 14:17 UTC, junghaesung79 commented on src/pages/Coop/components/Calendar/index.tsx
> +    const prevMonthDate = new Date(selectedDate);
함수 이름을 바꿔주면 더 좋을 것 같아요! 함수는 보통 동작하는 영어를 자주 사용하는데 지금의 명명은 그런 느낌이 들지 않는 것 같아요. 그리고 이 함수의 이름을 위해 이 코드 위쪽에 반환 값의 이름을 변경하여 사용하셨는데, 이럴 경우 나중에 리팩토링을 진행할 때 실수가 발생할 수도 있을 것 같아요. 맥락은 잘 모르지만 go 이런 것을 앞에 붙일 수 있을 것 같아요!

2024-10-15 14:17 UTC, junghaesung79 commented on src/pages/Coop/components/Calendar/index.tsx
> +  };
오잉? 이것도 함수명이었군요.. 더욱 실수하면 안 되는 코드네요.

2024-10-15 14:17 UTC, junghaesung79 commented on src/pages/Coop/components/Calendar/index.tsx
> +                    [styles.date]: true,
살짝 걱정이 드는 게, 달력을 보여주다보면 이전 달 말일이나 다음 달 초의 날짜가 이번 달 날짜와 겹쳐서 키가 중복되지는 않나요? 만약 키가 겹치면 개발자도구에서 경고를 보여줄 거예요.

2024-10-15 14:17 UTC, junghaesung79 commented on src/pages/Coop/components/DateMover/DateMover.module.scss
> +.button-next {
차라리 둘 다 같은 class명을 붙여서 이렇게 콤마 없이 스타일 을 줄 수 있을 것 같아요!

2024-10-15 14:17 UTC, junghaesung79 commented on src/pages/Coop/components/DateMover/DateMover.module.scss
> +  line-height: 160%; /* 28.8px */
주석~
한 번 깃허브 커밋 해보시겠어요? 이런 식으로 suggestion을 할 수 있는데 이때 여기서 바로 커밋이 가능하거든요!
```suggestion
  font-weight: 500;
  line-height: 160%;
```

2024-10-15 14:17 UTC, junghaesung79 commented on src/pages/Coop/components/DateMover/DateMover.module.scss
> +  line-height: 160%; /* 28.8px */
왼쪽의 Commit suggestion을 한 번 눌러보세요!

2024-10-15 14:17 UTC, junghaesung79 commented on src/pages/Coop/components/DateMover/DateMover.module.scss
> +    border-radius: 999px;
음... 상관 없긴 한데 저는 둥근 모양의 요소에도 정확한 radius를 먹여요ㅋㅎㅋㅎ 근거는 굳이 말하자면 읽을 때 크기 예상 가능?

2024-10-15 14:17 UTC, junghaesung79 commented on src/pages/Coop/components/DateMover/index.tsx
> +        onClick={onTodayClick}
정해진 건 아니지만, on~ 속성에 함수를 넣을 때 저는 handle~ 로 이름 붙일 것 같아요

2024-10-15 14:18 UTC, daepan approved these changes
수고하셨습니다.

2024-10-15 14:33 UTC, merged